# Generated by Django 2.2.6 on 2019-11-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='amostra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('x0', models.CharField(max_length=25)),
                ('x1', models.CharField(max_length=25)),
                ('x2', models.CharField(max_length=25)),
                ('x3', models.CharField(max_length=25)),
                ('x4', models.CharField(max_length=25)),
                ('x5', models.CharField(max_length=25)),
                ('x6', models.CharField(max_length=25)),
                ('x7', models.CharField(max_length=25)),
                ('x8', models.CharField(max_length=25)),
                ('x9', models.CharField(max_length=25)),
                ('x10', models.CharField(max_length=25)),
                ('x11', models.CharField(max_length=25)),
                ('x12', models.CharField(max_length=25)),
                ('x13', models.CharField(max_length=25)),
                ('x14', models.CharField(max_length=25)),
                ('x15', models.CharField(max_length=25)),
                ('x16', models.CharField(max_length=25)),
                ('x17', models.CharField(max_length=25)),
                ('x18', models.CharField(max_length=25)),
                ('x19', models.CharField(max_length=25)),
                ('x20', models.CharField(max_length=25)),
                ('x21', models.CharField(max_length=25)),
                ('x22', models.CharField(max_length=25)),
                ('x23', models.CharField(max_length=25)),
                ('x24', models.CharField(max_length=25)),
                ('media', models.CharField(max_length=25)),
                ('sigma', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='graphic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('year', models.CharField(max_length=4)),
                ('month', models.CharField(max_length=2)),
                ('day', models.CharField(max_length=2)),
                ('hour', models.CharField(max_length=2)),
                ('minu', models.CharField(max_length=2)),
                ('year1', models.CharField(max_length=4)),
                ('month1', models.CharField(max_length=2)),
                ('day1', models.CharField(max_length=2)),
                ('hour1', models.CharField(max_length=2)),
                ('minu1', models.CharField(max_length=2)),
                ('img', models.ImageField(blank=True, upload_to='graphs')),
            ],
        ),
    ]
