# Generated by Django 2.2.6 on 2019-11-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amostra',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='graphic',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/graphs/'),
        ),
    ]
