# Generated by Django 2.2.6 on 2019-11-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20191102_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='graphicForm2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
