# Generated by Django 2.2.6 on 2019-11-08 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_graphicform2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='graphicForm2',
        ),
    ]
