# Generated by Django 2.2.6 on 2019-11-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_delete_graphicform2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amostra',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
