# Generated by Django 2.2.6 on 2019-11-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20191128_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphic',
            name='dpm',
            field=models.CharField(default='2740', max_length=25),
            preserve_default=False,
        ),
    ]
