# Generated by Django 2.2.6 on 2019-11-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_graphic_dpm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic',
            name='rule1m',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='graphic',
            name='rule1s',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='graphic',
            name='rule2m',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='graphic',
            name='rule2s',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='graphic',
            name='rule3m',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='graphic',
            name='rule3s',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='graphic',
            name='rule4m',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='graphic',
            name='rule4s',
            field=models.BooleanField(default=False),
        ),
    ]
