# Generated by Django 2.2.6 on 2019-11-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20191128_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphic',
            name='tipo',
            field=models.BooleanField(default=False),
        ),
    ]
