# Generated by Django 2.2.6 on 2019-11-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_graphic_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphic',
            name='day',
        ),
        migrations.RemoveField(
            model_name='graphic',
            name='day1',
        ),
        migrations.RemoveField(
            model_name='graphic',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='graphic',
            name='hour1',
        ),
        migrations.RemoveField(
            model_name='graphic',
            name='minu',
        ),
        migrations.RemoveField(
            model_name='graphic',
            name='minu1',
        ),
        migrations.RemoveField(
            model_name='graphic',
            name='month',
        ),
        migrations.RemoveField(
            model_name='graphic',
            name='month1',
        ),
        migrations.RemoveField(
            model_name='graphic',
            name='year',
        ),
        migrations.RemoveField(
            model_name='graphic',
            name='year1',
        ),
        migrations.AddField(
            model_name='graphic',
            name='date1',
            field=models.DateTimeField(default='2019-12-10T08:30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graphic',
            name='date2',
            field=models.DateTimeField(default='2019-12-10T08:30'),
            preserve_default=False,
        ),
    ]
