# Generated by Django 2.2.6 on 2019-12-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20191129_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphic',
            name='LC',
            field=models.CharField(default='0', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graphic',
            name='LCs',
            field=models.CharField(default='0', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graphic',
            name='LIC',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graphic',
            name='LICs',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graphic',
            name='LIE',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graphic',
            name='LSC',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graphic',
            name='LSCs',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graphic',
            name='LSE',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
