# Generated by Django 2.2.6 on 2019-12-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_globalvar'),
    ]

    operations = [
        migrations.CreateModel(
            name='longGraphic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date1', models.DateTimeField()),
                ('date2', models.DateTimeField()),
                ('img', models.ImageField(blank=True, upload_to='static/graphs/')),
                ('cp', models.CharField(max_length=25)),
                ('cpk', models.CharField(max_length=25)),
                ('dpm', models.CharField(max_length=25)),
                ('LC', models.CharField(max_length=25)),
                ('LSC', models.CharField(max_length=25)),
                ('LIC', models.CharField(max_length=25)),
                ('LCs', models.CharField(max_length=25)),
                ('LSCs', models.CharField(max_length=25)),
                ('LICs', models.CharField(max_length=25)),
                ('LSE', models.CharField(max_length=25)),
                ('LIE', models.CharField(max_length=25)),
                ('rule1m', models.BooleanField(default=False)),
                ('rule2m', models.BooleanField(default=False)),
                ('rule3m', models.BooleanField(default=False)),
                ('rule4m', models.BooleanField(default=False)),
                ('rule1s', models.BooleanField(default=False)),
                ('rule2s', models.BooleanField(default=False)),
                ('rule3s', models.BooleanField(default=False)),
                ('rule4s', models.BooleanField(default=False)),
            ],
        ),
    ]
