# Generated by Django 2.2.6 on 2019-12-05 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_longgraphic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longgraphic',
            name='date1',
        ),
        migrations.RemoveField(
            model_name='longgraphic',
            name='date2',
        ),
        migrations.RemoveField(
            model_name='longgraphic',
            name='date_added',
        ),
    ]
