# Generated by Django 2.2.6 on 2019-12-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20191205_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humidity',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
