# Generated by Django 2.2.6 on 2019-12-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20191205_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humidity',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
