# Generated by Django 2.1.7 on 2019-06-15 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190615_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphic',
            name='date2',
        ),
    ]
