# Generated by Django 2.1.7 on 2019-06-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_graphic_date2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphic',
            name='name',
        ),
        migrations.AddField(
            model_name='graphic',
            name='day',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graphic',
            name='hour',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graphic',
            name='minu',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graphic',
            name='month',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
