# Generated by Django 2.1.7 on 2019-06-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20190615_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphic',
            name='day1',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graphic',
            name='hour1',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graphic',
            name='minu1',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graphic',
            name='month1',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graphic',
            name='year1',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
