# Generated by Django 2.1.7 on 2019-06-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20190615_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphic',
            name='name',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
