# Generated by Django 2.1.7 on 2019-06-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_graphic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphic',
            name='date1',
            field=models.DateTimeField(default='2019-06-15 22:52:34.810649'),
        ),
        migrations.AddField(
            model_name='graphic',
            name='date2',
            field=models.DateTimeField(default='2019-06-15 22:52:34.810649'),
        ),
    ]
