# Generated by Django 2.1.7 on 2019-06-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20190615_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphic',
            name='img',
            field=models.ImageField(default='', upload_to='graphs'),
            preserve_default=False,
        ),
    ]
