# Generated by Django 2.1.7 on 2019-06-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_graphic_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic',
            name='img',
            field=models.ImageField(blank=True, upload_to='graphs'),
        ),
    ]
