# Generated by Django 2.1.7 on 2019-06-16 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_graphic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amostra',
            name='key',
        ),
        migrations.RemoveField(
            model_name='graphic',
            name='date1',
        ),
        migrations.RemoveField(
            model_name='graphic',
            name='date2',
        ),
    ]
