# Generated by Django 2.1.7 on 2019-06-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20190616_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphic',
            name='Xlinha',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
