# Generated by Django 2.1.7 on 2019-07-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_graphic_xlinha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphic',
            name='Xlinha',
        ),
        migrations.AddField(
            model_name='amostra',
            name='sigma',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
