from django.db import models

class temperature(models.Model):
	date = models.DateTimeField(auto_now_add=True)
	x0 = models.CharField(max_length=25)
	x1 = models.CharField(max_length=25)
	x2 = models.CharField(max_length=25)
	x3 = models.CharField(max_length=25)
	x4 = models.CharField(max_length=25)
	x5 = models.CharField(max_length=25)
	x6 = models.CharField(max_length=25)
	x7 = models.CharField(max_length=25)
	x8 = models.CharField(max_length=25)
	x9 = models.CharField(max_length=25)
	x10 = models.CharField(max_length=25)
	x11 = models.CharField(max_length=25)
	x12 = models.CharField(max_length=25)
	x13 = models.CharField(max_length=25)
	x14 = models.CharField(max_length=25)
	x15 = models.CharField(max_length=25)
	x16 = models.CharField(max_length=25)
	x17 = models.CharField(max_length=25)
	x18 = models.CharField(max_length=25)
	x19 = models.CharField(max_length=25)
	x20 = models.CharField(max_length=25)
	x21 = models.CharField(max_length=25)
	x22 = models.CharField(max_length=25)
	x23 = models.CharField(max_length=25)
	x24 = models.CharField(max_length=25)
	media = models.CharField(max_length=25)
	sigma = models.CharField(max_length=25)
	def __str__(self):
		return str(self.date)

class humidity(models.Model):
	date = models.DateTimeField(auto_now_add=True)
	x0 = models.CharField(max_length=25)
	x1 = models.CharField(max_length=25)
	x2 = models.CharField(max_length=25)
	x3 = models.CharField(max_length=25)
	x4 = models.CharField(max_length=25)
	x5 = models.CharField(max_length=25)
	x6 = models.CharField(max_length=25)
	x7 = models.CharField(max_length=25)
	x8 = models.CharField(max_length=25)
	x9 = models.CharField(max_length=25)
	x10 = models.CharField(max_length=25)
	x11 = models.CharField(max_length=25)
	x12 = models.CharField(max_length=25)
	x13 = models.CharField(max_length=25)
	x14 = models.CharField(max_length=25)
	x15 = models.CharField(max_length=25)
	x16 = models.CharField(max_length=25)
	x17 = models.CharField(max_length=25)
	x18 = models.CharField(max_length=25)
	x19 = models.CharField(max_length=25)
	x20 = models.CharField(max_length=25)
	x21 = models.CharField(max_length=25)
	x22 = models.CharField(max_length=25)
	x23 = models.CharField(max_length=25)
	x24 = models.CharField(max_length=25)
	media = models.CharField(max_length=25)
	sigma = models.CharField(max_length=25)
	def __str__(self):
		return str(self.date)

class graphic(models.Model):
	tipo = models.BooleanField(default=False) #False = Humidity // True = Temperature
	date_added = models.DateTimeField(auto_now_add=True)
	date1 = models.DateTimeField(auto_now_add=False)
	date2 = models.DateTimeField(auto_now_add=False)
	img = models.ImageField(upload_to='static/graphs/', blank=True)
	cp = models.CharField(max_length=25)
	cpk = models.CharField(max_length=25)
	dpm = models.CharField(max_length=25)
	LC = models.CharField(max_length=25)
	LSC = models.CharField(max_length=25)
	LIC = models.CharField(max_length=25)
	LCs = models.CharField(max_length=25)
	LSCs = models.CharField(max_length=25)
	LICs = models.CharField(max_length=25)
	LSE = models.CharField(max_length=25)
	LIE = models.CharField(max_length=25)
	rule1m = models.BooleanField(default=False)
	rule2m = models.BooleanField(default=False)
	rule3m = models.BooleanField(default=False)
	rule4m = models.BooleanField(default=False)
	rule1s = models.BooleanField(default=False)
	rule2s = models.BooleanField(default=False)
	rule3s = models.BooleanField(default=False)
	rule4s = models.BooleanField(default=False)
	def __str__(self):
		return str(self.date_added)

class globalvar(models.Model):
	name = models.CharField(max_length=25)
	value = models.CharField(max_length=25)
	def __str__(self):
		return str(self.name)

class longgraphic(models.Model):
	tipo = models.BooleanField(default=False) #False = Humidity // True = Temperature
	img = models.ImageField(upload_to='static/graphs/', blank=True)
	cp = models.CharField(max_length=25)
	cpk = models.CharField(max_length=25)
	dpm = models.CharField(max_length=25)
	LC = models.CharField(max_length=25)
	LSC = models.CharField(max_length=25)
	LIC = models.CharField(max_length=25)
	LCs = models.CharField(max_length=25)
	LSCs = models.CharField(max_length=25)
	LICs = models.CharField(max_length=25)
	LSE = models.CharField(max_length=25)
	LIE = models.CharField(max_length=25)
	rule1m = models.BooleanField(default=False)
	rule2m = models.BooleanField(default=False)
	rule3m = models.BooleanField(default=False)
	rule4m = models.BooleanField(default=False)
	rule1s = models.BooleanField(default=False)
	rule2s = models.BooleanField(default=False)
	rule3s = models.BooleanField(default=False)
	rule4s = models.BooleanField(default=False)
	def __str__(self):
		return str(self.cp)

